apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-zee-deploy
  labels:
    app: bankapp-zee-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp-zee-app
  template:
    metadata:
      labels:
        app: bankapp-zee-app
    spec:
      containers:
      - name: bankapp-zee-container
        image: zeehan0133/bankapp-zee-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-zee-np-service1
  labels:
    app: bankapp-zee-app1
spec:
  selector:
    app: bankapp-zee-app

  type: NodePort
  ports:
  - nodePort: 31111    
    port: 8081
    targetPort: 8081
